######################################################################
# Files
######################################################################

# the website root (/var/www/physics) -- pages (see below) are named as
# "rootDir/pages.pageUrl[lang]".
rootDir: "./test"
#rootDir: "/var/www/physics"

# Where to cache wiki pages. (NO trailing slash)
cacheDir: "./sivut"

# The confluence wiki url
fetchUrl: "https://wiki.helsinki.fi/plugins/viewsource/viewpagesrc.action?pageId="

# Used to fetch i18n course names from weboodi
weboodiUrl: "https://weboodi.helsinki.fi/hy/opintjakstied.jsp?html=1&Kieli="

# We cache i18n names for courses here when we fetch them from weboodi.
# If the names have changed, please either delete this file or alter its
# contents. The new i18n names are then fetched on next rebuild.
oodiNameFile: "./oodi.names"


######################################################################
# Page generation
######################################################################

# In which languages to generate the pages
languages:
   - en
   - fi
   - se

# Which wiki pages to use as source and how to name them.
# - pageId: confluence wiki id
# - pageTitle: title of the page in different languages
# - pageUrl: The locations of the page in different languages
pages:
   -
      pageId: "155236781"
      pageTitle:
         fi: "Fysiikka"
         se: "Fysik - Undervisning på finska"
         en: "Physics"
      pageUrl:
         fi: "/opetus/kurssit/fysiikka"
         se: "/svenska/opetus/kurssit/fysiikka"
         en: "/english/studying/courses/physics"
   -
      pageId: "133439230"
      pageTitle:
         fi: "Ruotsinkielinen fysiikan opetus"
         se: "Fysik - Undervisning på svenska"
         en: "Physics - Teaching in Swedish"
      pageUrl:
         fi: "/opetus/kurssit/ruotsinkielinen_fysiikka"
         se: "/svenska/opetus/kurssit/fysik"
         en: "/english/studying/courses/physics_swedish"
   -
      pageId: "133439202"
      pageTitle:
         fi: "Fysiikan opettajankoulutus"
         se: "Fysiklärare"
         en: "Physics teacher"
      pageUrl:
         fi: "/opetus/kurssit/fysiikan_opettajankoulutus"
         se: "/svenska/opetus/kurssit/fysiikan_opettajankoulutus"
         en: "/english/studying/courses/physics_teachers"
   -
      pageId: "133439172"
      pageTitle:
         fi: "Teoreettinen fysiikka"
         se: "Teoretisk fysik"
         en: "Theoretical physics"
      pageUrl:
         fi: "/opetus/kurssit/teoreettinen_fysiikka"
         se: "/svenska/opetus/kurssit/teoreettinen_fysiikka"
         en: "/english/studying/courses/theoretical_physics"
   -
      pageId: "133439148"
      pageTitle:
         fi: "Geofysiikka"
         se: "Geofysik"
         en: "Geophysics"
      pageUrl:
         fi: "/opetus/kurssit/vesivaipan_geofysiikka"
         se: "/svenska/opetus/kurssit/vesivaipan_geofysiikka"
         en: "/english/studying/courses/geophysics"
   -
      pageId: "133439021"
      pageTitle:
         fi: "Meteorologia"
         se: "Meteorologi"
         en: "Meteorology"
      pageUrl:
         fi: "/opetus/kurssit/meteorologia"
         se: "/svenska/opetus/kurssit/meteorologia"
         en: "/english/studying/courses/meteorology"
   -
      pageId: "133439114"
      pageTitle:
         fi: "Tähtitiede"
         se: "Astronomi"
         en: "Astronomy"
      pageUrl:
         fi: "/opetus/kurssit/tahtitiede"
         se: "/svenska/opetus/kurssit/tahtitiede"
         en: "/english/studying/courses/astronomy"

######################################################################
# Internationalisation in output. Map text fragments+language pairs to
# i18n texts
######################################################################
i18n:
   "pääaineopetus":
      fi: "PÄÄAINEOPETUS"
      en: "MAJOR SUBJECT STUDIES"
      se: "HUVUDÄMNESSTUDIER"
   "sivuaineopetus":
      fi: "SIVUAINEOPETUS"
      en: "MINOR SUBJECT STUDIES"
      se: "BIÄMNESSTUDIER"

   "perusopinnot":
      fi: "Perusopinnot"
      en: "Basic studies"
      se: "Grundstudier"
   "aineopinnot":
      fi: "Aineopinnot"
      en: "Intermediate studies"
      se: "Ämnesstudier"
   "syventävät opinnot":
      fi: "Syventävät opinnot"
      en: "Advanced studies"
      se: "Avancerade studier"
   "muut opinnot":
      fi: "Muut opinnot"
      en: "Other studies"
      se: "Andra studier"

   "pakolliset opinnot":
      fi: "Pakolliset opinnot"
      en: "Mandatory studies"
      se: "Obligatoriska studier"
   "valinnaiset opinnot":
      fi: "Valinnaiset opinnot"
      en: "Optional studies"
      se: "Valfria studier"

   "Kaikki":
      en: "All"
      se: "Allt"
   "Kieli":
      fi: "Opetuskieli"
      en: "Teaching language"
      se: "Undervisningsspråk"
   "Kevät":
      en: "Spring"
      se: "Vår"
   "Syksy":
      en: "Autumn"
      se: "Höst"
   "Kesä":
      en: "Summer"
      se: "Sommar"

   "koodi":
      fi: "WebOodi-koodi"
      en: "WebOodi code"
      se: "WebOodi-kod"
   "kurssin nimi":
      fi: "Kurssin nimi"
      en: "Course name"
      se: "Kursnamn"
   "periodi":
      fi: "Periodi"
      en: "Period"
      se: "Period"
   "Lukukausi":
      en: "Semester"
      se: "Termin"
   "op":
      en: "ECTS"
      se: "sp"
   "kotisivu":
      fi: "Kotisivu"
      en: "Homepage"
      se: "Hemsida"
   "Taso":
      en: "Study level"
      se: "Level"
   "opetuskieli":
      fi: "Opetuskieli"
      en: "Language"
      se: "Språk"
   "väli(vuosia)":
      fi: "Toistuu"
      en: "Interval between courses (years)"
      se: "Intervall"

   "en":
      fi: "Englanniksi"
      en: "In English"
      se: "På engelska"
   "fi":
      fi: "Suomeksi"
      en: "In Finnish"
      se: "På finska"
   "se":
      fi: "Ruotsiksi"
      en: "In Swedish"
      se: "På svenska"

   "Päivitetty":
      fi: "Sivu päivitetty viimeksi"
      en: "Page was last updated"
      se: "Updaterad"

   "Kaikki kurssit":
      en: "All courses"
      se: "Alla kurser"

   "aputeksti":
      fi:
         >
            Klikkaa kurssikoodista WebOodiin.
            Harmaat kurssit eivät ole saatavilla tällä lukukaudella (2015-2016).
            Näiden kurssien lisäksi fysiikan laitoksella voi opiskella tiedekunnan yhteisiä opintoja, sivuaineopintoja, ja kieliopintoja jne.

            Mikäli tiedot WebOodissa eivät tyydytä, ota yhteyttä luennoitsijaan.
            Mikäli luennoitsijan sähköpostia ei löydy, ota yhteys [phyinfo@helsinki.fi](mailto:phyinfo@helsinki.fi).

            Katso opetusperiodit [täältä](http://www.physics.helsinki.fi/opetus/opetusohjelma/1415/opetusohjelma.html).
      en:
         >
            Clicking the WebOodi code of the course goes to the study guide ([WebOodi](http://weboodi.helsinki.fi)).
            Courses grayed out are not available this academic year (2015-2016).
            In addition to these courses there are also faculty courses, courses in minor subjects, language courses etc.

            If information on the study guide page is not satisfactory for you, please do not hesitate to contact the lecturer.
            If lecturer email is not available, please contact [phyinfo@helsinki.fi](mailto:phyinfo@helsinki.fi).

            See dates for the periods I-IV [here](http://www.physics.helsinki.fi/opetus/opetusohjelma/1415/opetusohjelma.html).

      se:
         >
            Klicka på kurskoden för att besöka WebOodi.
            De gråa kurserna är inte tillgängliga det här läsåret (2015-2016)
            Förutom de här kurserna kan man vid institutionen för fysik även studera
            fakultetens gemensamma studier, biämnesstudier, språkstudier osv.

            Om informationen i WebOodi är bristfällig, kontakta föreläsaren.
            Om föreläsaren inte har en e-postadress, kontakta
            [phyinfo@helsinki.fi](mailto:phyinfo@helsinki.fi).

            Se föreläsningsperioderna
            [här](http://www.physics.helsinki.fi/opetus/opetusohjelma/1415/opetusohjelma.html).

   "1. aerosoli- ja ympäristöfysiikka (markku kulmala ja antti lauri)":
      fi: "1. Aerosoli- ja ympäristöfysiikka (Markku Kulmala ja Antti Lauri)"
      en: "1. Aerosol and environmental physics"
      se: "1. Aerosol- och miljöfysik"

   "1. dynaaminen ja fysikaalinen meteorologia":
      fi: "1. Dynaaminen ja fysikaalinen meteorologia"
      en: "1. Dynamic and physical meteorology"
      se: "1. DYNAMISK OCH FYSIKALISK METEOROLOGI"

   "2. avaruusfysiikka (emilia kilpua ja hannu koskinen)":
      fi: "2. Avaruusfysiikka (Emilia Kilpua ja Hannu Koskinen)"
      en: "2. Space physics"
      se: "2. Rymdfysik"

   "2. mikrometeorologia ja kemiallinen meteorologia":
      fi: "2. Mikrometeorologia ja kemiallinen meteorologia"
      en: "2. Micrometeorology and chemical meteorology"
      se: "2. Mikrometeorologi och kemikalisk meteorologi"

   "3. bio- lääketieteellisen fysiikka (arto annila ja sauli savolainen)":
      fi: "3. Bio- lääketieteellisen fysiikka (Arto Annila ja Sauli Savolainen)"
      en: "3. Bio-medical physics"
      se: "3. Bio- och medicinsk fysik"

   "4. elektroniikka ja teollisuussovellukset (edward häggström)":
      fi: "4. Elektroniikka ja teollisuussovellukset (Edward Häggström)"
      en: "4. Electronics and industry applications"
      se: "4. Elektronik och industritillämpningar"

   "5. hiukkas- ja ydinfysiikka ja kosmologia (katri huitu ja paula eerola)":
      fi: "5. Hiukkas- ja ydinfysiikka ja kosmologia (Katri Huitu ja Paula Eerola)"
      en: "5. Particle and nuclear physics, and cosmology"
      se: "5. Partikel- och kärnfysik och kosmologi"

   "6. laskennallinen fysiikka (kai nordlund ja antti kuronen)":
      fi: "6. Laskennallinen fysiikka (Kai Nordlund ja Antti Kuronen)"
      en: "6. Computational physics"
      se: "6. Beräkningsfysik"

   "7. materiaali- ja nanofysiikka (antti kuronen ja mikko hakala)":
      fi: "7. Materiaali- ja nanofysiikka (Antti Kuronen ja Mikko Hakala)"
      en: "7. Material and nano-physics"
      se: "7. Material- och nanofysik"

   "8. kiinteän maan geofysiikka (ilmo kukkonen ja emilia koivisto)":
      fi: "8. Kiinteän maan geofysiikka (Ilmo Kukkonen ja Emilia Koivisto)"
      en: "8. Solid earth geophysics"
      se: "8. Fasta jordens geofysik"

   "a. ydinaineksen kurssit":
      fi: "A. Ydinaineksen kurssit"
      en: "A. Core material courses"
      se: "A. Kärnstudiernas kurser"

   "b. erikoistumiskurssit":
      fi: "B. Erikoistumiskurssit"
      en: "B. Specialization courses"
      se: "B. Specialiseringskurser"

   "b. ydinainesta täydentävät kurssit":
      fi: "B. Ydinainesta täydentävät kurssit"
      en: "B. Core material complementing courses"
      se: "B. Kärnstudiernas fördjupade kurser"

   "kevät, kenttä":
      fi: "Kevät, kenttä"
      en: "Spring, field"
      se: "Vår, fält"
   "syksy, kenttä":
      fi: "Syksy, kenttä"
      en: "Autumn, field"
      se: "Höst, fält"
   "kesä, kenttä":
      fi: "Kesä, kenttä"
      en: "Summer, field"
      se: "Sommar, fält"

   "tammikuu":
      fi: "Tammikuu"
      en: "January"
      se: "Januari"
   "helmikuu":
      fi: "Helmikuu"
      en: "February"
      se: "Februari"
   "maaliskuu":
      fi: "Maaliskuu"
      en: "Mars"
      se: "Mars"
   "huhtikuu":
      fi: "Huhtikuu"
      en: "April"
      se: "April"
   "toukokuu":
      fi: "Toukokuu"
      en: "May"
      se: "Maj"
   "kesäkuu":
      fi: "Kesäkuu"
      en: "June"
      se: "Juni"
   "heinäkuu":
      fi: "Heinäkuu"
      en: "July"
      se: "Juli"
   "elokuu":
      fi: "Elokuu"
      en: "August"
      se: "Augusti"
   "syyskuu":
      fi: "Syyskuu"
      en: "September"
      se: "September"
   "lokakuu":
      fi: "Lokakuu"
      en: "October"
      se: "Oktober"
   "marraskuu":
      fi: "Marraskuu"
      en: "November"
      se: "November"
   "joulukuu":
      fi: "Joulukuu"
      en: "December"
      se: "December"


#-------------------------------------------------------------------------------------
# Fix to remove extra translation not found warning when running script.
#-------------------------------------------------------------------------------------
   "1. ":
      en: "1. "
      se: "1. "
   "2. ":
      en: "2. "
      se: "2. "
   "3. ":
      en: "3. "
      se: "3. " 
   "4. ":
      en: "4. "
      se: "4. "
   "5. ":
      en: "5. "
      se: "5. "
   "6. ":
      en: "6. "
      se: "6. "
   "7. ":
      en: "7. "
      se: "7. "
   "8. ":
      en: "8. "
      se: "8. "
   "9. ":
      en: "9. "
      se: "9. "


#-------------------------------------------------------------------------------------
# Temporary hotfix to remove extra translation not found warning when running script.
#-------------------------------------------------------------------------------------

# This is probably a temporary line in the Wiki Table
   "IV (elokuu 2015, Hyytiälässä?)":
      en: "IV (August 2015, in Hyytiälä?)"
      se: "IV (Augusti 2015, i Hyytiälä?)"

# This is probably a spelling error
   "I -II":
      fi: "I-II"
      en: "I-II"
      se: "I-II"

######################################################################
# The wiki table
######################################################################

# List of lists of categories: Every sublist should contain categories that
# exclude each other. The first sublist (in order) is the most relevant grouping
# (the highest categories), the second is a subgroup of the first and so on.
categories:
   -
     - "pääaineopetus"
     - "sivuaineopetus"
   -
     - "perusopinnot"
     - "aineopinnot"
     - "syventävät opinnot"
     - "muut opinnot"
   - 
     - "1. "
     - "2. "
     - "3. "
     - "4. "
     - "5. "
     - "6. "
     - "7. "
     - "8. "
     - "9. "
   - 
     - "pakolliset opinnot"
     - "valinnaiset opinnot"
   -
     - "a. "
     - "b. "

# The default category level when nestling categories.
categoryLevel: 1

#-------------------------------------------------------------------------------
# Column headers and specifications. The titles of the different column headers
# must align with `toLower wikiTableColName`.
#
#       Try to get the widths to sum up to 100% in total.
#       CSS syntax is allowed (%-sign not mandatory)
#
# The columns here don't have to come in the same order as presented in the
# web page.
#-------------------------------------------------------------------------------
columnHeaders:
   colCode:
       title:   "koodi"
       width:   "15%"
   colCourseName:
       title:   "kurssin nimi"
       width:   "45%"
   colPeriod:
       title:   "periodi"
       width:   "10%"
   colRepeats:
       title:   "väli(vuosia)"
       width:   "10%"
   colLang:
       title:   "opetuskieli"
       width:   "10%"
   colWebsite:
       title:   "kotisivu"
       width:   "10%"


# HTML class of second column td when that course IS arranged this year
classCur:      "highlight-green"

